---
ssh: ascross

package: qbittorrent
name: qBittorrent
version: 3.3.13
firmware: 2.6.0

config:
  general:
    developer: The qBittorrent project
    website: http://www.qbittorrent.org
    maintainer: mafredri
    email: mafredri+adm@gmail.com
    depends: []
    conflicts: []
    package: "PACKAGE"
    name: "NAME"
    version: "VERSION"
    architecture: "ARCHITECTURE"
    firmware: "FIRMWARE"
  adm-desktop:
    app:
      port: 8181
      protocol: http
      type: custom
      url: /
    privilege:
      accessible: users
      customizable: true
  register:
    symbolic-link:
      /bin:
        - "qbittorrent-nox"
    boot-priority:
      start-order: 20
      stop-order: 80
    port:
      - 8181

case_sensitive: false
runpath: /usr/local/AppCentral/qbittorrent/lib
updated_libstdcpp: true
root: /usr
files:
  - /usr/bin/qbittorrent-nox
  - /usr/lib/libboost_system.so*
  - /usr/lib/libQt5Solutions_LockedFile-2.4.so*
  - /usr/lib/libQt5Solutions_SingleApplication-2.6.so*
  - /usr/lib/libQt5Core.so*
  - /usr/lib/libQt5Network.so*
  - /usr/lib/libQt5Concurrent.so*
  - /usr/lib/libQt5Xml.so*
  - /usr/lib/libtorrent-rasterbar.so*
  - /usr/lib/libpcre16.so*
  - /usr/lib/libGeoIP.so*
  - /usr/lib/libdouble-conversion.so*
